# Form implementation generated from reading ui file 'AddClass.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ClassManager import Manager
from log import logger
from PyQt6.QtWidgets import QMessageBox

class Ui_form_addClass(object):
    def setupUi(self, form_addClass):
        form_addClass.setObjectName("form_addClass")
        form_addClass.resize(400, 150)
        form_addClass.setWindowIcon(QtGui.QIcon('./ai.ico'))
        form_addClass.setMinimumSize(QtCore.QSize(400, 150))
        form_addClass.setMaximumSize(QtCore.QSize(400, 150))
        self.lineEdit_classes = QtWidgets.QLineEdit(form_addClass)
        self.lineEdit_classes.setGeometry(QtCore.QRect(80, 60, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_classes.setFont(font)
        self.lineEdit_classes.setObjectName("lineEdit_classes")
        self.label_newclass = QtWidgets.QLabel(form_addClass)
        self.label_newclass.setGeometry(QtCore.QRect(10, 70, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_newclass.setFont(font)
        self.label_newclass.setObjectName("label_newclass")
        self.btn_add = QtWidgets.QPushButton(form_addClass)
        self.btn_add.setGeometry(QtCore.QRect(320, 100, 75, 24))
        self.btn_add.setObjectName("btn_add")
        self.label_help = QtWidgets.QLabel(form_addClass)
        self.label_help.setGeometry(QtCore.QRect(10, 20, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_help.setFont(font)
        self.label_help.setStyleSheet("color: rgb(10, 10, 250);")
        self.label_help.setObjectName("label_help")

        self.label_hint = QtWidgets.QLabel(form_addClass)
        self.label_hint.setGeometry(QtCore.QRect(10, 34, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_hint.setFont(font)
        self.label_hint.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_hint.setObjectName("label_hint")

        self.retranslateUi(form_addClass)
        QtCore.QMetaObject.connectSlotsByName(form_addClass)
        #################### our code
        self.btn_add.clicked.connect(self.onBtn_allClasses_Clicked)
        self.class_manager = Manager()

    def show_message(self,msg, title):
        dlg = QtWidgets.QMessageBox()
        dlg.setWindowIcon(QtGui.QIcon('./ai.ico'))
        dlg.setText(msg)
        dlg.setIcon(QMessageBox.Icon.Information)
        dlg.setWindowTitle(title)
        dlg.defaultButton()
        dlg.exec()

    def onBtn_allClasses_Clicked(self):
        try:
            line = self.lineEdit_classes.text()
            cls_cnt = self.class_manager.addClasses(line)
            self.lineEdit_classes.clear()
            if cls_cnt==0:
                self.show_message("Nothing is saved. Please check whether you have entered classes correctly in the edit box", "Please check")
            else:
                self.show_message(str(cls_cnt)+ " classes saved Successfully!!", "Success")
        except Exception as e:
            logger.error("classes not saved,"+str(e))


    def retranslateUi(self, form_addClass):
        _translate = QtCore.QCoreApplication.translate
        form_addClass.setWindowTitle(_translate("form_addClass", "Add Class"))
        self.label_newclass.setText(_translate("form_addClass", "New Class:"))
        self.btn_add.setText(_translate("form_addClass", "Add"))
        self.label_help.setText(_translate("form_addClass", "Add multiple classes separeted by comma"))
        self.label_hint.setText(_translate("form_addClass", "classes with special characters in them, will be ignored"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     form_addClass = QtWidgets.QWidget()
#     ui = Ui_form_addClass()
#     ui.setupUi(form_addClass)
#     form_addClass.show()
#     sys.exit(app.exec())
